version: '3'
networks:
  keycloak_network:
    driver: bridge
services:
  postgres:
    image: postgres
    networks:
      - keycloak_network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: 
      - db:/var/lib/postgresql/data
  keycloak-server:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak-server
    depends_on:
      - postgres
    # ports:
    #   - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - keycloak_network
  keycloak-server-1:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak-server-1
    depends_on:
      - postgres
    # ports:
    #   - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - keycloak_network
  haproxy:
    image: keycloak-haproxy
    ports:
      - 80:80
    depends_on:
      - keycloak-server
      - keycloak-server-1
    networks:
      - keycloak_network
  # nginx-proxy:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - keycloak_network
volumes:
  db:
    driver: local